### ISSUE TITLE
Application error, since pulling latest changes

### ISSUE THREAD

**Issue by Nan0Scho1ar** [org-roam/org-roam-ui#33] opened 2021-08-03 06:08 UTC
I have been using org-roam-ui  for the past few days and the only issue I had was [this one](https://github.com/org-roam/org-roam-ui/issues/18#event-5095523451)

I've been following the issue and saw it was recently fixed so I updated to get the new changes.

Now when I run `org-roam-ui-mode` instead of a gorgeous graph I get white screen with the error "Application error: a client-side exception has occurred (developer guidance)."
I'm not really sure how to debug this further so let me know if there are any steps I can take to help debug the issue.
(I use doom emacs if that is relevant)
Cheers

**Comment by Nan0Scho1ar** [comment] 2021-08-03 06:20
If I roll back to commit 177f4b38d2dcf59861198db1113a2cf7ef59f5d9 then the issue disappears

**Comment by ThomasFKJorna** [comment] 2021-08-03 08:23
Could you share your browsers console log? Another thing you could try is to open devtools, go to either Storage or Application > Storage, then Local Storage and delete all the keys there. I should really provide a command to do this because it can sometimes lead to some issues when we change settings.

Also, which browser are you using?

**Comment by kongds** [comment] 2021-08-03 09:43
Same issue here,  I try to clear cache, but not work
Browser:  Chrome  92.0.4515.131
Console log:
![image](https://user-images.githubusercontent.com/19282154/127994420-488cdf3c-ac21-4da5-8abd-27fd5ad133c1.png)

**Comment by ThomasFKJorna** [comment] 2021-08-03 09:54
Do you perhaps not use tags in your notes? That might be it

**Comment by ThomasFKJorna** [comment] 2021-08-03 09:56
If I send "nil" instead of the tags, I get a very similar error 
![image](https://user-images.githubusercontent.com/21983833/127996781-8c838eda-baca-454c-a992-77c54b967fee.png)

**Comment by kongds** [comment] 2021-08-03 09:59
![image](https://user-images.githubusercontent.com/19282154/127997101-7f28729e-70ec-4f62-a257-bf745a69e995.png)
Do you means this tag?

**Comment by ThomasFKJorna** [comment] 2021-08-03 09:59
Yeah

**Comment by ThomasFKJorna** [comment] 2021-08-03 10:00
I just pushed a (potential) fix for this, could you try it out?

**Comment by kongds** [comment] 2021-08-03 10:01
But i don't use it in my note
![image](https://user-images.githubusercontent.com/19282154/127997425-4022c1ee-b23f-497c-b492-01d1efeb5fa0.png)

**Comment by ThomasFKJorna** [comment] 2021-08-03 10:02
Then that was probably it. If you did not have any tags at all, it would try to list all your tags anyway, but couldn't find any. Now it does not do that anymore, so it should work.

**Comment by kongds** [comment] 2021-08-03 10:08
Thank you, it works.

**Comment by ThomasFKJorna** [comment] 2021-08-03 10:09
Fantastic!

**Comment by Nan0Scho1ar** [comment] 2021-08-03 14:42
I just pulled down the most recent changes and the issue is resolved for me too. I think this can probably be resolved.
Cheers for addressing it so promptly :)

**Closed** 2021-08-03 14:49 UTC

**Comment by maikol-solis** [comment] 2021-08-03 16:49
Hi!, I have this issue with my files. This is the error in the browser console:  

![image](https://user-images.githubusercontent.com/4078489/128054350-9db37f7e-3afa-4629-8633-569b1f47b552.png)

Reviewing a little, I don't use a lot `FILETAGS` but I have some `ROAM_TAGS` that I didn't migrate to V2 across all my files. I don't know if this is interfering with `orui`. 

Thanks.

**Comment by ThomasFKJorna** [comment] 2021-08-03 16:57
Hmm the issue is probably that we still don't have a way to easily flush your cache. 
Could you open orui in incognito as well and see if that works?
If it does. Could you go to developer options, "Application > Local Storage" and delete the "filter" key? If that still does not work, please delete the "visuals" key as well, and if that doesn't work, the rest.

If it did not work in incognito something more serious is wrong.

**Comment by maikol-solis** [comment] 2021-08-03 17:04
Thanks @ThomasFKJorna . 

It does work in incognito mode 

![image](https://user-images.githubusercontent.com/4078489/128055924-fe82263b-53ba-45f3-b41c-36a74be6b89b.png)

I deleted everything here 

![image](https://user-images.githubusercontent.com/4078489/128056579-476d04da-3fee-4b3b-bc97-0af417948401.png)

and now the graph is working again. 

Thanks.

**Comment by ThomasFKJorna** [comment] 2021-08-03 17:07
Np! It was my fault for changing the configuration anyway 😅
