### ISSUE TITLE
Application error: a client-side exception has occurred (developer guidance)

### ISSUE THREAD

**Issue by Arahnoid** [org-roam/org-roam-ui#39] opened 2021-08-04 14:52 UTC
When I try to run roam ui `M-x roam-ui-open` I see the following error in the Firefox Developer Edition 91.0b9 (64-bit) browser on MacOS Big Sur 11.5.

```
Application error: a client-side exception has occurred (developer guidance).
```

In Brave or Safari everything works fine.

**Comment by matthew-piziak** [comment] 2021-08-04 14:59
@Arahnoid Possible a duplicate of https://github.com/org-roam/org-roam-ui/issues/34

I bet the only reason it works on Brave and Safari is because it's a problem with cached browser-local org-roam-ui settings, and you simply haven't broken it on those browsers yet. Me, I've managed to break Firefox, Chromium, and qutebrowser because I couldn't stop fidgeting. If you are able to clear the place in Firefox where the settings are stored, it should restore the UI.

**Comment by Arahnoid** [comment] 2021-08-04 15:07
@matthew-piziak thanks for hinting what may be the issue.

This is what I did in the main menu opened History / Clear Recent History...

<img width="486" alt="image" src="https://user-images.githubusercontent.com/726874/128205402-fda3ccdf-d47b-47ae-aa5f-b92d235de2a1.png">

Everything works now. ;)

**Comment by matthew-piziak** [comment] 2021-08-04 20:43
@Arahnoid Glad to hear it!

**Closed** 2021-08-06 01:34 UTC
