### ISSUE TITLE
[BUG] Preview node shows entire file instead of just subtree

### ISSUE THREAD

**Issue by ngharrison** [org-roam/org-roam-ui#174] opened 2021-12-01 04:10 UTC
**Describe the bug**
When single clicking on a node in the browser graph to preview a node, the sidebar that shows the contents of the node always shows the entire file instead of just the subtree of that node.

**To Reproduce**
1. Open org-roam-ui
2. Click on a node that corresponds to a heading within a file
3. Look at the right sidebar

**Expected behavior**
Only the subtree of that heading is shown.

**What browser were you using?**
Chrome

**Comment by rasendubi** [comment] 2021-12-01 11:56
Duplicate of #106

**Closed** 2021-12-01 23:10 UTC
Labels: bug
