### ISSUE TITLE
Filter setting - inverted Orphan switch behavior

### ISSUE THREAD

**Issue by cube48** [org-roam/org-roam-ui#21] opened 2021-08-01 20:56 UTC
It looks like the logic of the Orphan switch in the filter setting is inverted - graph shows the orphans (unlinked files/nodes) when the switch is disabled and vice versa.

**Comment by ThomasFKJorna** [comment] 2021-08-01 22:49
This works as intended: you turn on the filter to get rid of the orphans. I would not want to have hiding users' nodes to be the default setting (off).

The parent toggle is the odd one out, but that is because it's something that org-roam-ui provides on top of org-roam: these links are not there by default and we have to construct them. Since we are not "filtering" the links, we have it inverted for now, but probably will change that behavior later once people are used to those links being there.

This conception of the toggles might make less sense atm, but once we introduce more filters I think having the "on" state remove things make more sense, otherwise it would act as a whitelist which becomes more unmanageable for things like tags. 

Hope that makes sense! I will close this issue now as we probably won't be changing this.

**Closed by ThomasFKJorna** 2021-08-01 22:49 UTC

**Comment by cube48** [comment] 2021-08-02 04:39
I see, makes sense as 'filter active'. My misunderstanding comes perhaps from Logseq where the same switch does the oposite. But it's true that there the panel is not called 'filter' but 'nodes'. 

Sorry for the noise. And thanks for awesome work!

**Comment by ThomasFKJorna** [comment] 2021-08-02 09:03
No worries! I was basing this behavior more on Obsidian, who uses it in the same way, but the other way around makes sense too.

**Comment by kennethbruskiewicz** [comment] 2022-03-08 21:10
There is a use-case for this, specifically when you want to view only all of the nodes that are "under-developed". There's a greater marginal benefit to developing more connections for under-connected pieces of knowledge, than adding to more central nodes when they are already quite thoroughly explored.

If you were to advise someone who would want to develop this feature in a fork, what would you recommend?
